In [1]:
import numpy as np

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
a = [0, 1, 2, 3, 4, 5]
arr = np.array(a)

In [4]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

2. Given a NumPy array 'arr', check if its data type is float64.

In [6]:
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of arr is float64.")
else:
    print("The data type of arr is not float64.")


The data type of arr is float64.


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [7]:
arr = np.array([2 + 5j, 9 - 2j, 3 + 4j], dtype=np.complex128)
print(arr)

[2.+5.j 9.-2.j 3.+4.j]


4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print(arr_float32)

[1. 2. 3. 4. 5.]


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [9]:
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.5 2.6 3.7]


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [10]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype


my_array = np.array([[1, 2, 3], [4, 5, 6]])


shape, size, dtype = array_attributes(my_array)

print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [11]:
def array_dimension(arr):
    return arr.ndim
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


dim_1d = array_dimension(arr_1d)
dim_2d = array_dimension(arr_2d)
dim_3d = array_dimension(arr_3d)

print("Dimensionality of arr_1d:", dim_1d)
print("Dimensionality of arr_2d:", dim_2d)
print("Dimensionality of arr_3d:", dim_3d)


Dimensionality of arr_1d: 1
Dimensionality of arr_2d: 2
Dimensionality of arr_3d: 3


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [12]:
def item_size_info(arr):
   
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

my_array = np.array([[1, 2, 3], [4, 5, 6]])

item_size, total_size = item_size_info(my_array)

print("Item Size (bytes per element):", item_size)
print("Total Size (bytes):", total_size)


Item Size (bytes per element): 8
Total Size (bytes): 48


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [13]:
import numpy as np

def array_strides(arr):
    return arr.strides

my_array = np.array([[1, 2, 3], [4, 5, 6]])

strides = array_strides(my_array)

print("Strides:", strides)


Strides: (24, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [14]:
import numpy as np

def shape_stride_relationship(arr):
    
    shape = arr.shape
    strides = arr.strides
    return shape, strides

my_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


11. Create a function create_zeros_array that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.

In [15]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

zeros_array = create_zeros_array(5)
print("Zeros Array:", zeros_array)


Zeros Array: [0. 0. 0. 0. 0.]


12. Write a function create ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.

In [16]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

ones_matrix = create_ones_matrix(3, 4)

print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13. Write a function generate_range_array' that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified step.

In [17]:
import numpy as np

def generate_range_array(start, stop, step):
   
    return np.arange(start, stop, step)

range_array = generate_range_array(0, 10, 2)
print("Range Array:", range_array)


Range Array: [0 2 4 6 8]


14. Design a function 'generate_linear_space that takes two floats 'start', 'stop', and an integer 'num'as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop' (inclusive).

In [18]:
import numpy as np

def generate_linear_space(start, stop, num):
   
    return np.linspace(start, stop, num)

linear_space_array = generate_linear_space(0, 10, 5)
print("Linear Space Array:", linear_space_array)


Linear Space Array: [ 0.   2.5  5.   7.5 10. ]


15. Create a function create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size 'n x n' using 'numpy.eye.

In [19]:
import numpy as np

def create_identity_matrix(n):
   
    return np.eye(n)

identity_matrix = create_identity_matrix(3)
print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.

In [20]:
def list_to_numpy_array(py_list):
    
    return np.array(py_list)

my_list = [1, 2, 3, 4, 5]

numpy_array = list_to_numpy_array(my_list)
print("NumPy Array:", numpy_array)

NumPy Array: [1 2 3 4 5]


17. Create a NumPy array and demonstrate the use of numpy.view' to create a new array object with the same data

In [21]:
original_array = np.array([1, 2, 3, 4, 5])

view_array = original_array.view()

view_array[0] = 100

print("Original Array:", original_array)
print("View Array:", view_array)


Original Array: [100   2   3   4   5]
View Array: [100   2   3   4   5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [22]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
   
    return np.concatenate((arr1, arr2), axis=axis)


array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])


concatenated_array = concatenate_arrays(array1, array2, axis=0)
print(concatenated_array)

concatenated_array_axis_1 = concatenate_arrays(array1, array2, axis=1)
print(concatenated_array_axis_1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy. concatenate

In [23]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])  
array2 = np.array([[7, 8], [9, 10]])       

concatenated_array = np.concatenate((array1, array2), axis=1)

print(array1)
print(array2)
print(concatenated_array)


[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [24]:
import numpy as np

def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

# Vertically stack the arrays
stacked_array = stack_arrays_vertically([array1, array2, array3])


print(array1)
print(array2)
print(array3)
print(stacked_array)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [25]:
import numpy as np

def create_integer_range_array(start, stop, step):
    
    return np.arange(start, stop + 1, step, dtype=int)


integer_range_array = create_integer_range_array(0, 10, 2)
print("Integer Range Array:", integer_range_array)


Integer Range Array: [ 0  2  4  6  8 10]


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (Inclusive).

In [26]:
import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

equally_spaced_values = generate_equally_spaced_values()
print(equally_spaced_values)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [27]:
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, num=5)

# Example usage:
logarithmically_spaced_values = generate_logarithmically_spaced_values()
print("Logarithmically Spaced Values between 1 and 1000:")
print(logarithmically_spaced_values)


Logarithmically Spaced Values between 1 and 1000:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [28]:
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0        3        9       70
1       16       23       36
2       97       93       24
3       57       23       83
4       24       68       36


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [29]:
def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [-1, 2, -3, 4, -5],
        'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)
df_modified = replace_negatives_with_zeros(df, 'A')
print(df)
print(df_modified)


   A   B
0  0  10
1  2 -20
2  0  30
3  4 -40
4  0  50
   A   B
0  0  10
1  2 -20
2  0  30
3  4 -40
4  0  50


26. Access the 3rd element from the given NumPy array.
arr np.array([10, 20, 30, 48, 50])

In [30]:
arr = np.array([10, 20, 30, 48, 50])
third_element = arr[2]
print("The 3rd element of the array:", third_element)

The 3rd element of the array: 30


27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [31]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element_at_index_1_2 = arr_2d[1, 2]
print("The element at index (1, 2) from the 2D array:", element_at_index_1_2)

The element at index (1, 2) from the 2D array: 6


28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr np.array([3, 8, 2, 10, 5, 7])

In [32]:
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
elements_greater_than_5 = arr[mask]
print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]

print("Sliced array:", sliced_arr)


Sliced array: [3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr_2d np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]

print("Sub-array:")
print(sub_array)


Sub-array:
[[2 3]
 [5 6]]


31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [35]:

def extract_elements(arr, indices):
    indices = np.array(indices)
    indices = indices[(indices >= 0) & (indices < arr.size)]
    return arr.flatten()[indices]

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = [1, 5, 8]

result = extract_elements(arr, indices)
print(result)


[2 6 9]


32. Create a NumPy function that filters elements greater than a threshold from a given ID array using boolean indexing.

In [36]:
def filter_ids(arr, threshold):
    mask = arr > threshold
    return filtered_ids
ids = np.array([1, 5, 10, 15, 20])
threshold = 10
filtered_ids = filter_ids(ids, threshold)
print(filtered_ids)


NameError: name 'filtered_ids' is not defined

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
def extract_elements_3d(arr, indices_dim1, indices_dim2, indices_dim3):
    
    indices_dim1 = np.array(indices_dim1)
    indices_dim2 = np.array(indices_dim2)
    indices_dim3 = np.array(indices_dim3)
    
    indices_dim1 = indices_dim1[(indices_dim1 >= 0) & (indices_dim1 < arr.shape[0])]
    indices_dim2 = indices_dim2[(indices_dim2 >= 0) & (indices_dim2 < arr.shape[1])]
    indices_dim3 = indices_dim3[(indices_dim3 >= 0) & (indices_dim3 < arr.shape[2])]
    

    extracted_elements = arr[indices_dim1[:, np.newaxis, np.newaxis], 
                             indices_dim2[np.newaxis, :, np.newaxis],
                             indices_dim3[np.newaxis, np.newaxis, :]]
    
    return extracted_elements

arr_3d = np.arange(27).reshape(3, 3, 3)  # Creating a 3D array for demonstration

indices_dim1 = [0, 1]
indices_dim2 = [0, 2]
indices_dim3 = [1, 2]

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(result)


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [37]:
import numpy as np

def satisfy_conditions(arr, condition1, condition2):
    
    mask1 = condition1(arr)
    mask2 = condition2(arr)
    
   
    combined_mask = np.logical_and(mask1, mask2)
    
    
    filtered_elements = arr[combined_mask]
    
    return filtered_elements


arr = np.array([1, 2, 3, 4, 5])
condition1 = lambda x: x > 2
condition2 = lambda x: x % 2 == 0

result = satisfy_conditions(arr, condition1, condition2)
print(result)


[4]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [38]:
def extract_elements_2d(arr, row_indices, col_indices):
    
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    
    
    row_indices = row_indices[(row_indices >= 0) & (row_indices < arr.shape[0])]
    col_indices = col_indices[(col_indices >= 0) & (col_indices < arr.shape[1])]
    
    
    extracted_elements = arr[row_indices, col_indices]
    
    return extracted_elements


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = [0, 1, 2]
col_indices = [1, 0, 2]

result = extract_elements_2d(arr_2d, row_indices, col_indices)
print(result)


[2 4 9]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [39]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arrl of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arrl using NumPy broadcasting

In [40]:
import numpy as np

# Create the arrays
arr1 = np.array([[2, 3, 4]])  
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  


result = arr1 * arr2

print(result)


ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

38. Given a 1D array arrl of shape (1, 4) and a 2D array arr2 of shape (4,3), add arrl to each row of arr2 using NumPy broadcasting.

In [41]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr1 + arr2

print(result)


ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

39. Consider two arrays arrl of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting

In [42]:
arr1 = np.array([[1],
                 [2],
                 [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


40. Given arrays arrl of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting

In [43]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])
arr2 = arr2[:, np.newaxis, :]

result = arr1 * arr2

print(result)


ValueError: operands could not be broadcast together with shapes (2,3) (2,1,2) 

41. Calculate column-wise mean for the given array:
35°C Clear
arr np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_means = np.mean(arr, axis=0)

print("Column-wise mean:", column_means)


Column-wise mean: [2.5 3.5 4.5]


42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_values_in_rows = np.max(arr, axis=1)
print(max_values_in_rows)


[3 6]


43. For the given array, find indices of maximum value in each column. arr= np.array([[1, 2, 3], [4, 5, 6]])

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices_in_columns = np.argmax(arr, axis=0)
print(max_indices_in_columns)

[1 1 1]


44. For the given array, apply custom function to calculate moving sum along rows. arr np.array([[1, 2, 3], [4, 5, 6]])

In [47]:
def moving_sum(row):
    result = np.cumsum(row)
    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(moving_sum_result)

[[ 1  3  6]
 [ 4  9 15]]


45. In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]])

In [48]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions 'm' rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [49]:
import numpy as np

def reshape_array(arr, m, n):
    reshaped_matrix = arr.reshape(m, n)
    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])

m = 2
n = 3

reshaped_arr = reshape_array(original_array, m, n)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
import numpy as np

def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.
array1= np.array([[1, 2], [3, 4]])
array2= np.array([[5, 6], [7, 8]])


In [51]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along rows:")
print(result)

result = concatenate_arrays(array1, array2, axis=1)
print(result)


Concatenated along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [52]:
import numpy as np

def split_array(original_array, num_splits, axis=0):
    split_arrays = np.split(original_array, num_splits, axis=axis)
    return split_arrays

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = split_array(original_array, num_splits=3, axis=0)
print("Split along rows:")
for arr in result:
    print(arr)

result = split_array(original_array, num_splits=3, axis=1)
print("\nSplit along columns:")
for arr in result:
    print(arr)


Split along rows:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along columns:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array np.array([1, 2, 3, 4, 5])
indices_to_insert [2, 4]
values_to_insert = [10, 11] indices_to_delete = [1, 3]

In [53]:
import numpy as np

def insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    for idx, val in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, val)

   
    original_array = np.delete(original_array, indices_to_delete)

    return original_array


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


result_array = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10 11  4  5]


51. Create a NumPy array 'arrl with random integers and another array 'arr2' with integers from 1 to 10. Perform element-wise addition between 'arrl` and `arr2`.

In [54]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 100, size=(5, 5))

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result = arr1 + arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nElement-wise addition result:")
print(result)


ValueError: operands could not be broadcast together with shapes (5,5) (10,) 

52. Generate a NumPy array `arrl with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract arr2` from `arrl` element-wise.

In [55]:

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)


Array 1:
[10  9  8  7  6  5  4  3  2  1]

Array 2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array arrl with random integers and another array 'arr2" with integers from 1 to 5. Perform element-wise multiplication between 'arrl' and 'arr2'.

In [56]:

arr1 = np.random.randint(1, 10, size=(3, 3))  # Example size, adjust as needed

arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

54. Generate a NumPy array 'arrl with even integers from 2 to 10 and another array 'arr2' with integers from 1 to 5. Perform element-wise division of 'arrl' by 'arr2'.

In [57]:
import numpy as np

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)


Array 1:
[ 2  4  6  8 10]

Array 2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


55. Create a NumPy array 'arrl with integers from 1 to 5 and another array 'arr2' with the same numbers reversed. Calculate the exponentiation of arrl raised to the power of 'arr2' element-wise.

In [58]:
import numpy as np

arr1 = np.arange(1, 6)

arr2 = arr1[::-1]

result = np.power(arr1, arr2)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)


Array 1:
[1 2 3 4 5]

Array 2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [59]:
import numpy as np

def count_substring_occurrences(arr, substring):
    return sum(1 for string in arr if substring in string)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

occurrences = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}' in the array: {occurrences}")


Occurrences of 'hello' in the array: 3


57. Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAl', 'GPT'])
arr
np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [60]:
import numpy as np

def extract_uppercase_characters(arr):
    uppercase_chars = ''.join([char for string in arr for char in string if char.isupper()])
    return uppercase_chars

arr1 = np.array(['Hello', 'World', 'OpenAl', 'GPT'])
arr2 = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


uppercase_chars1 = extract_uppercase_characters(arr1)
uppercase_chars2 = extract_uppercase_characters(arr2)

print("Uppercase characters in arr1:", uppercase_chars1)
print("Uppercase characters in arr2:", uppercase_chars2)


Uppercase characters in arr1: HWOAGPT
Uppercase characters in arr2: HWOAIGPT


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr= np.array(['apple', 'banana', 'grape', 'pineapple'])

In [61]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    
    replace_func = np.vectorize(lambda s: s.replace(old_substring, new_substring))
    
    return replace_func(arr)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'ap', 'an')
print(new_arr)


['anple' 'banana' 'grane' 'pineanple']


59. Write a function that concatenates strings in a NumPy array element-wise.
arr1= np.array(['Hello', 'World']) arr2 np.array(['Open', 'AI'])

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2):
    concatenated = np.char.add(arr1, arr2)
    return concatenated

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_arrays(arr1, arr2)
print(result)


60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr np.array(['apple', 'banana', 'grape', 'pineapple'])

In [64]:
import numpy as np

def longest_string_length(arr):

    lengths = np.char.str_len(arr)
    
    max_length = np.max(lengths)
    return max_length


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print("Length of the longest string:", result)


Length of the longest string: 9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [65]:
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)

median = np.median(dataset)

variance = np.var(dataset)

std_dev = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset: [809 955 417 603  92 289 411 355 984 950 134 337 737 402 687 680 301 882
   7 307 278 150 913 223 647 933 676 916   4 168 889 152 904 753  61 150
 156  99 692 696 975 638 150 392 836 936 735 581 315 400 262 790 526 979
  34 449 348 109 382   4 317 752 657 709 434 470 615 665 309 940  25 952
 889 478 903 589 557 351 433 821 796 634 164 432 940 588 583 829 182  30
 831 762 389 971 691 915  25 975 475 441]
Mean: 531.59
Median: 569.0
Variance: 90926.80189999998
Standard Deviation: 301.54071350316855


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [66]:
random_numbers = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("Random numbers:", random_numbers)
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


Random numbers: [18 11 52 43  2 97 50 97  7 96 31 20 97 61 53 81  2 85 48 18 12 38 56 16
 63  7 48  7 28 91 57 80 27  1 83 37 11 74 17 21 65 25 73 51 11 77  7 64
 10 12]
25th percentile: 13.0
75th percentile: 64.75


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 'corrcoef function.

In [67]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation coefficient:", correlation_coefficient)


Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Correlation coefficient: -0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's 'dot' function.

In [68]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Result of matrix multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]
Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of matrix multiplication:
[[ 58  64]
 [139 154]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [69]:
array = np.random.randint(10, 1001, size=50)

percentiles = np.percentile(array, [10, 25, 50, 75, 90])

first_quartile = percentiles[1]
median = percentiles[2]
third_quartile = percentiles[3]

print("Array:", array)
print("10th percentile:", percentiles[0])
print("First quartile (25th percentile):", first_quartile)
print("Median (50th percentile):", median)
print("Third quartile (75th percentile):", third_quartile)
print("90th percentile:", percentiles[4])


Array: [612  43  41 773 687 398 154 995 266 917 672 939 995 621 154 586 661 989
 216 335 311 744 760 915 266 575 540 713 753 280 740 223 685 143 405  66
 489 669 856 677 257 483 627 954  12 945 751 549 946 848]
10th percentile: 152.9
First quartile (25th percentile): 287.75
Median (50th percentile): 624.0
Third quartile (75th percentile): 758.25
90th percentile: 945.1


66. Create a NumPy array of integers and find the index of a specific element.

In [70]:


array = np.array([1, 2, 3, 4, 5])

element = 3
index = np.where(array == element)[0]

if len(index) > 0:
    print("Index of", element, ":", index[0])
else:
    print("Element not found in the array.")


Index of 3 : 2


67. Generate a random NumPy array and sort it in ascending order.

In [71]:

random_array = np.random.randint(1, 100, size=10)

sorted_array = np.sort(random_array)

print("Random array:", random_array)
print("Sorted array in ascending order:", sorted_array)


Random array: [73 96 18 81 36 38 73 10 39  5]
Sorted array in ascending order: [ 5 10 18 36 38 39 73 73 81 96]


68. Filter elements >20 in the given NumPy array.
arr np.array([12, 25, 6, 42, 8, 30])

In [72]:

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original array:", arr)
print("Filtered elements greater than 20:", filtered_arr)


Original array: [12 25  6 42  8 30]
Filtered elements greater than 20: [25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array.
arr np.array([1, 5, 8, 12, 15])

In [73]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print(filtered_arr)


[12 15]


70. Filter elements which are >= 20 and <= 40 from a given NumPy array.
arr
np.array([10, 20, 38, 48, 50])

In [77]:
arr = np.array([10, 20, 38, 48, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print(filtered_arr)


[20 38]


71. For the given NumPy array, check its byte order using the 'dtype" attribute byteorder.
arr
np.array([1, 2, 3])

In [78]:

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Byte order:", byte_order)


Byte order: =


72. For the given NumPy array, perform byte swapping in place using byteswap().
arr np.array ([1, 2, 3], dtype=np.int32)

In [79]:

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

print(arr)


[16777216 33554432 50331648]


73. For the given NumPy array, swap its byte order without modifying the original array using 'newbyteorder()'.
arr np.array([1, 2, 3], dtype=np.int32)

In [80]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

arr_swapped = arr.newbyteorder()

print("Original array:")
print(arr)
print("Array with swapped byte order:")
print(arr_swapped)


Original array:
[1 2 3]
Array with swapped byte order:
[16777216 33554432 50331648]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
arr np.array([1, 2, 3], dtype=np.int32)

In [82]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Determine system endianness
sys_endianness = sys.byteorder

# Conditionally swap byte order based on system endianness
if sys_endianness == 'little':
    arr_swapped = arr.newbyteorder('big')  # Swap to big-endian
elif sys_endianness == 'big':
    arr_swapped = arr.newbyteorder('little')  # Swap to little-endian
else:
    # Handle the case if endianness is unknown
    print("Unknown system endianness")

print("Original array:")
print(arr)
print("Array with swapped byte order based on system endianness:")
print(arr_swapped)


Original array:
[1 2 3]
Array with swapped byte order based on system endianness:
[16777216 33554432 50331648]


75. For the given NumPy array, check if byte swapping is necessary for the current system using 'dtype' attribute byteorder'.
arr np.array([1, 2, 3], dtype=np.int32)

In [83]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

byte_swapping_needed = arr.dtype.byteorder != '='

if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Byte swapping is not necessary for the current system.


76. Create a NumPy array 'arrl with values from 1 to 10. Create a copy of 'arrl named 'copy_arr and modify an element in 'copy_arr. Check if modifying copy_arr affects 'arrl'.

In [2]:
arrl = np.arange(1, 11)

copy_arr = arrl.copy()
copy_arr[0] = 100

print("Original array 'arrl':", arrl)
print("Modified array 'copy_arr':", copy_arr)


Original array 'arrl': [ 1  2  3  4  5  6  7  8  9 10]
Modified array 'copy_arr': [100   2   3   4   5   6   7   8   9  10]


77. Create a 2D NumPy array 'matrix of shape (3, 3) with random integers. Extract a slice 'view_slice from the matrix. Modify an element in 'view_slice' and observe if it changes the original matrix.

In [3]:
matrix = np.random.randint(0, 10, size=(3, 3))

view_slice = matrix[:2, :2]

view_slice[0, 0] = 100

print("Original matrix:")
print(matrix)

print("\nModified view_slice:")
print(view_slice)


Original matrix:
[[100   2   0]
 [  4   3   4]
 [  0   2   7]]

Modified view_slice:
[[100   2]
 [  4   3]]


78. Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 'view_b'from array_a' and broadcast the addition of 5 to view_b. Check if it alters the original 'array_a`.

In [4]:

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :2]

view_b += 5

print("Original array 'array_a':")
print(array_a)

print("\nModified slice 'view_b':")
print(view_b)


Original array 'array_a':
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified slice 'view_b':
[[ 6  7]
 [ 9 10]]


79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view 'reshaped_view of shape (4, 2) from orig_array. Modify an element in 'reshaped_view' and check if it reflects changes in the original'orig_array.

In [5]:

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100

print(orig_array)

print("\nModified view 'reshaped_view':")
print(reshaped_view)


[[100   2   3   4]
 [  5   6   7   8]]

Modified view 'reshaped_view':
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


80. Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy of elements greater than 5. Modify an element in 'data_copy' and verify if it affects the original'data'.

In [8]:
import numpy as np

data = np.random.randint(0, 10, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0, 0] = 100

print("Original array 'data':")
print(data)

print("\nModified copy 'data_copy':")
print(data_copy)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [9]:
import numpy as np

# Create matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Addition operation
addition_result = A + B

# Subtraction operation
subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


82. Generate two matrices 'C' (3x2) and 'D' (2x4) and perform matrix multiplication.

In [10]:

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

result = np.dot(C, D)

print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nResult of matrix multiplication (C dot D):")
print(result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Result of matrix multiplication (C dot D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


83. Create a matrix 'E' and find its transpose.

In [11]:


E = np.array([[1, 2, 3],
              [4, 5, 6]])

E_transpose = np.transpose(E)

print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


84. Generate a square matrix 'F' and compute its determinant.

In [13]:

F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)

print("\nDeterminant of matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


85. Create a square matrix `G` and find its inverse.

In [14]:
G = np.array([[1, 2],
              [3, 4]])

inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)

print("\nInverse of matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
